### ISSUE TITLE
Hide dropdown when there are no matching items

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#140]
The empty dropdown for custom input values (which do not match any item in the dropdown) causes some confusion for end users, and it should be hidden.

**Comment by jounik** [comment]
Just noticed, that the dropdown triangle button doesn’t revert to it’s "closed" state, and you need to click it twice to reopen the dropdown. It feels like we should do that as well when hiding the empty dropdown, so that it feels more like it’s just being closed.

**Comment by Saulis** [comment]
Yes, the combo-box stays "open" when the list is hidden. Just reverting the icon to "closed" state wouldn't therefore help the double-click issue, the first click would also then close the box.

I think we should just replace the icon with something distinctly different from "open" and "closed" states.

**Comment by platosha** [comment]
Like @saulis said, it’s not enough to just change the icon to “closed”.

If we would properly change the combo-box state to become “closed” when there’s no matching items, it would be bad as well. It would be an unexpectedly caused close:
- The user hasn’t done anything to close the combo-box yet.
- The input stays focused.
- It would require user to reopen the combo-box manually to see the items again, if we press backspace a couple of times.

Changing the icon to something different is also not a good idea for me: it would blur the state indication. Would seem like the combo-box is neither opened nor closed, but in a strange third state.

Would it be better to show the empty dropdown instead of hiding it (and having a confusing state) or closing the combo-box (and having an unexpected state change). We could add a “No results found” in case when there’re no matching items. Select2 goes this way: https://select2.github.io/examples.html The state is consistent and clearly expressed there.

**Comment by samiheikki** [comment]
I would prefer the @platosha suggested way of showing "No results found" option when there are no matching items.

**Comment by jounik** [comment]
We tried to find an improvement to the design for this, and @tuomasnironen drew a few more mockups of an alternative. I’ll discuss those briefly with him first and we’ll share them then with the rest of the team.

The problem with a solution like "No results found" might confuse the user again into believing that what he wrote in the input is not accepted. It enforces the idea of the input just being a filter for the dropdown items. This is exactly where the user confusion comes from, that the component visually looks like a "select" but is actually also an input field. 

Also, I disagree about the icon/dropdown state. When we hide the dropdown (no matching items), to the user it’s the same thing as closing it. It works analogous to opening the dropdown when the user starts typing to filter. In that case the user hasn’t do anything else either to open the dropdown, just typed in the input (the user can focus the input with the tab key without opening the dropdown). And so, we definitely should not require the user to manually reopen the dropdown, but it should always open automatically when the user types in the field and there is at least one matching item.

Select2, like the name indicates, is just a select, not a combo box, so the user can never use a custom value there. And in that case, using something like "No matching results" is a good choice.

**Comment by platosha** [comment]
@jounik right, there're 2 basic cases of combo-box: input with suggested values values (accepts everything you type), and a select-like box with filter (doesn't accept non-listed options). FYI: while working on #96, we currently decided to disable custom input values in the combo-box by default. This makes it to behave like in the latter case.

**Comment by jounik** [comment]
Discussed offline: as part of #96 we are most likely introducing a property to disable/enable custom input values. Therefore we probably need two different solutions to this issue.

Is it okay if we implement those as part of #96, or would that need a separate issue?

**Comment by platosha** [comment]
#96 introduces a whole lot of changes already, I'd prefer to have a separate issue for that.
