### ISSUE TITLE
Research iOS viewport scrolling issue

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#2]
Research ways to mitigate iOS viewport scrolling in combination with fixed positioning.

**Comment by tomivirkki** [comment]
Problems with iOS when fullscreen popup is open:

1. Fixed -> absolute
- Problem: If the pop-up contains an input and it's focused, all elements with position:fixed are changed to position:absolute automatically and the position computed by iron-fit-behavior no longer applies.
- Current solution: On iOS the dropdown is forced position:absolute always, position computing is overridden with custom version that translates the overlay correctly with help of getBoundingClientRect()

2. Input is centered on focus
- Problem: Whenever an input field is focused, iPhone Safari moves the viewport in order to center the input to the remaining viewport (the space left unused after opening the virtual keyboard)
- Current solution: We reset the scrollPosition asynchronously whenever the dropdown receives ontouchend. We still see a noticeable glitch from the effect.

3. Double tap
- Problem: Double-tapping a position makes the viewport zoom/shift so that the position is centered to the viewport.
- Current solution: We reset the scrollPosition asynchronously whenever the dropdown receives ontouchend. We still see a noticeable glitch from the effect.

4. Opening address bar
- Problem: Opening the address bar while the dropdown is open reduces the viewport height slightly which may shift elements in the bottom of the screen out of view
- Current solution: We listen to iron-resize events on the dropdown and force a resize for the content

5. Remaining vertical space
- Problem: IOS virtual keyboard doesn't resize the viewport but is rather an overlay on top of it. There's no proper way to measure the exact height of virtual keyboard
- Current solution: On input focus we count on iOS trying to move the input field in the center of the view (as described earlier). We utilize this in estimating a size for the remaining vertical space in view. Still missing a minimum height (33vh or so). Still need a solution for iPad...

6. Touch move dragging
- Problem: Even with the keyboard open, the user can touch drag the dropdown out of view
- Current solution: We prevent default behaviour on touchmove

7. Orientation change
- Problem: Switching between portrait and landscape orientations resizes the viewport
- Current solution: We listen to iron-resize events on the dropdown and force a resize for the content

8. iPad vs iPhone
- Problem: Unlike iPhone, iPad doesn't really try to center the focused input but just brings it to the viewport. Our current approach on trying to estimate the remaining viewport fails because of that. Consider some other approach in detecting the available viewport space on iPad.

Prototype with the current approach at ios-fullscreen branch (still under work)

**Comment by Saulis** [comment]
To be continued... #9

**Comment by jounik** [comment]
The fullscreen mode should only apply on iPhone by default (viewports
smaller than about 500px). The breakpoint should probably be customizable,
but for 1.0 we can fix it if needed.

**Comment by jounik** [comment]
Great job on the research and the documentation of all the issues!

**Comment by Saulis** [comment]
We had this idea of just closing the keyboard in iPhone when the user starts scrolling by removing the focus from the input field. Would be nicely straight forward to implement and reliable method. What do you think? @tuomasnironen was OK with it.

**Comment by tuomasnironen** [comment]
I liked the simplicity of the solution and couldn't think of any accessibility issues it might introduce. The only thing I was wondering was that should there be some kind of floating "keyboard icon" at the bottom corner of the viewport, or something clickable, where the user could quickly refocus the input field and get the keyboard visible again? The same kind of button/icon was suggested by many end users when I tested the datepicker prototypes (there was problems finding a way how to input dates with keyboard on mobile).

**Comment by Saulis** [comment]
@jounik is the keyboard hiding approach OK for you to start work with?

**Comment by jounik** [comment]
@Saulis yeah, I think it’s a good option for 1.0 at least, to circumvent the iOS issues. Perhaps it’s even the best solution usability wise. We’ll see.
