### ISSUE TITLE
item value of "" causes weird behaviors

### ISSUE THREAD

**Issue by ktiedt** [vaadin/vaadin-combo-box#202]
if items array has a value of "" at least as a first value (haven't tested otherwise) it completely breaks the display/setting of the value property in the combobox (it always resets to "")

**Comment by tomivirkki** [comment]
Alright, did some research on this. The proposed fix is at
https://github.com/vaadin/vaadin-combo-box/tree/fix/empty-item

Main reason for the value display failing was because of how Polymer's get() api was used in `vaadin-combo-box._getItemValue`: empty string item (falsy) would cause the get() to switch to using the component itself as the root object.

Fixing that alone wasn't enough though. Iron-list doesn't handle empty strings in the items array too well: when iron-list's `_getNormalizedItem` get's invoked it throws a `RangeError` (due to the empty string item being falsy).

Working around this required some changes to combo box code so `_getNormalizedItem` wouldn't get invoked for the empty item value :/

Last but not least, according to our bower.json we currently support iron-list from version 1.0.0 up and at least 1.0.0 completely seems to ignore empty items. So this branch can't be merged until we ramp up the minimum version and that can't be done before the next minor release.

**Comment by platosha** [comment]
How is it going to work with object items case, when one of the item objects is like `{label: '(empty item)', value: ''}`?

I would expect it to work as with a regular item, so that `combobox.value = '';` selects this item and shows “(empty item)” text in the combobox. This would make it possible to customize the text shown for the empty value.

**Comment by tomivirkki** [comment]
We're postponing this for now since iron-list doesn't support empty strings as items and vaadin-combo-box currently depends on it.

**Comment by platosha** [comment]
Seems to work fine as of now. Most probably fixed by https://github.com/vaadin/vaadin-combo-box/commit/0e7c88ff2e95091d0cc5c8c3898e452fefbdbf5f, where we’ve stopped relying on the `selectedItem` property of `<iron-list>`.
