### ISSUE TITLE
override clear

### ISSUE THREAD

**Issue by depeele** [vaadin/vaadin-combo-box#243]
It would be nice to have a way to change the behavior of "clear" to be functionally equivalent to "cancel" (or expose a validator e.g. the `iron-validatable-behavior.validator` attribute) -- particularly when custom input is disabled.

For my particular use-case, an empty value for the field is not a valid option.

**Comment by depeele** [comment]
One option would be to include a `disable-clear` attribute:

```javascript

  _hideClearIcon: function(value, opened) {
  },

```

**Comment by depeele** [comment]
I've submitted a pull-request that addresses this: #244

**Comment by jouni** [comment]
#198 should satisfy this use case as well, as you can can choose to not provide a clear button next to your input.

**Comment by platosha** [comment]
Hi! Now that we have #198 implemented, could you please try if it resolves the issue for you?

**Comment by depeele** [comment]
Unless I'm missing something, #198 doesn't solve the hiding of the clear button.

The following example provided in #198 doesn't work for me at all:
```
<vaadin-combo-box>
  <paper-input class="input">
    <paper-icon-button icon="arrow-drop-down" suffix class="toggle-button"></paper-icon-button>
  </paper-input>
</vaadin-combo-box>
```

I can cause the clear button to be removed visually in the following way...
```
<vaadin-combo-box ...>
  <div class='clear-button style='display:none;'></div>
</vaadin-combo-box>
```

But even with this, there is styling in `vaadin-combo-box.html` that cannot be over-ridden and pushes the text aside when then control is `opened` to make room for a visually non-existent clear button:
```
:host([opened][has-value]) #input {
  padding-right: 60px;
  margin-right: -32px;
}
```

For small fields, this shift completely hides the current selection in the input area.

**Comment by tehapo** [comment]
The mentioned "examples" in #198 were more or less only meant as an inspiration to communicate the general idea. The final implementation is slightly different from these.

In your case, you could use the `vaadin-combo-box-light` element. For example something like the following.
```html
<vaadin-combo-box-light attr-for-value="value">
  <paper-input class="input" label="Dummy Label">
    <paper-icon-button
      suffix
      class="toggle-button rotate-on-open"
      icon="vaadin-combo-box:arrow-drop-down">
    </paper-icon-button>
  </paper-input>
</vaadin-combo-box-light>

```

This approach has two downsides at the moment.

1) I noticed a regression bug in the element while trying out the example. However the fix is already in review. 😄  See #302
2) To get the exact look and feel of the original `vaadin-combo-box`, you need to apply some CSS styles to the `paper-input` and `paper-icon-button`.

Please also take a look at the documentation for this custom input feature:
https://vaadin.com/docs/-/part/elements/vaadin-combo-box/vaadin-combo-box-customization.html
