### ISSUE TITLE
Implement 'change' event

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#271]
- 'change' is the standard name in w3c for value changes:  http://www.w3schools.com/jsref/event_onchange.asp `The onchange event occurs when the value of an element has been changed.` 
- Hummingbird assumes that all Inputs update value property and fire a 'change' event
- Polymer is firing 'change' in inputs, text-area etc.

Additionally in the combo-box the change event coming from the underlying input is leaking out to the element, and it's observed before the actual value is updated which could be confusing for the user

**Comment by KyleCrowley** [comment]
+1 for this. I find myself writing extra code that I _should not_ have to due to reasons similar to this, especially when working with a `<vaadin-combo-box>`.

As we speak, I am writing multiple event handlers to that do the same thing all because the `<vaadin-combo-box>` fires events not in-line with the Polymer/w3c standard. 

It's possible to develop a workaround, but why supercede **BOTH** w3c AND Polymer standards? 

Sorry if I'm ranting but this is an odd design choice.

**Comment by Saulis** [comment]
@KyleCrowley can you please try if branch `feature/change-event` works for you?

**Comment by KyleCrowley** [comment]
@Saulis Sorry. Didn't see this until now. However, just tested with the 1.1.2 and it's working wonderfully from what I can see from this (brief) test. 

Awesome work. Thanks a bunch!

**Comment by Saulis** [comment]
Glad to hear!

**Comment by hamzaislam** [comment]
Please see [#385](https://github.com/vaadin/vaadin-combo-box/issues/385). The "change" event should only fire as result of a gesture, not when value is selected programatically
