### ISSUE TITLE
styling of items in combo-box, and more mixins

### ISSUE THREAD

**Issue by mbana** [vaadin/vaadin-combo-box#275]
Hi,

Is it possible to style the items that appear in the combo? I've noticed that the overlay is placed right at the end of the dom, a bit strange, but fine.

Could you please expose some more mixins.

**Comment by tony19** [comment]
I needed to style the items in the overlay because it wasn't picking up the font size from my shared styles for some reason. I tried various CSS rules to target the overlay to no avail.

As a hacky workaround, I had to imperatively set the overlay's font size:
```
// <vaadin-combo-box id="input">
this.$.input.$.overlay.$.scroller.style.fontSize = '1.4rem';
```

**Comment by Saulis** [comment]
Hi!

The overlay is indeed directly under body to mitigate some overlapping issues with fixed elements. 

That, however makes it harder to target styles and mixins for a specific overlay since it doesn't have any unique identifier.

We will be looking into this while implementing #165 – customising and styling items will definitely be one of the next features we'll implement.

**Comment by Saulis** [comment]
I'm going to close this ticket as #165 was closed – we'll be releasing the new custom item template support shortly. Meanwhile, you can already check the `master` branch how it works. 

Feel free to re-open the ticket or open a new one if there are some use cases you feel is not achievable.
