### ISSUE TITLE
Value in Detail is [object Object] if you dont set the item-value-path

### ISSUE THREAD

**Issue by Bretto** [vaadin/vaadin-combo-box#296]
I have: ```items= [{id:1, name:'Brett', ... }]```
and on my selection I would like the all object back, ( I am not set the item-value-path purposefully )
```
<vaadin-combo-box
        label="Tags"
        item-label-path="name"
        [items]="tags"
        (value-changed)="onSelect($event)"></vaadin-combo-box>
```

now the value in the detail Object is [object Object]... how can I get the value back ? Is this a bug ?

**Comment by platosha** [comment]
This is intentional. The `value` property is always a string.

If you don’t set `itemValuePath`, then its default value of `"value"` is in use. And if there is no value property in the selected object, then it uses `selectedItem.toSting()`, that is why you have the default string representation `"[object Object]"` in the value.

Please use `selectedItem` if you want the full object back.

**Comment by Bretto** [comment]
Thanks for the clarification, Where do you set and get the ```selectedItem``` plz ?

**Comment by platosha** [comment]
The `selectedItem` property is read-only, there is no set. Set the `value` property with a string value to change the combo-box value. Mind that you have to specify the correct `item-value-path` in this case.

As for the `get`, you can listen for `selected-item-changed`, like you did in the neighbour issue #295. But, apparently there an issue with multiple calls. In case if the `value-changed` event works better, you can listen to it and get the `selectedItem` using a template reference variable:

```typescript
<vaadin-combo-box
        #tagsBox
        label="Tags"
        item-label-path="name"
        [items]="tags"
        (value-changed)="onSelect(tagsBox.selectedItem)"></vaadin-combo-box>
```
