### ISSUE TITLE
Basic accessibility support (ARIA roles)

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#34]
- See how the Framework combobox works
- See also Polymer `<paper-dropdown-menu>`
- http://www.w3.org/TR/wai-aria/roles#combobox
- http://www.w3.org/TR/wai-aria/roles#listitem
- Tests should assert that correct attributes are in correctomundo places
- Ask help from the Framework team & UX team
- Figure out how to verify we have all the needed attributes?
- Chrome has an Accessibility Developer Tools extension

**Comment by manolo** [comment]
DOD: 
- Set the correct roles to the text input, dropdown, list and items so as the reader correctly says:
  -  When the user is on a combobox
   - If he push arrow down the reader informs about dropdown opened
  - The reader should inform as well about the number of items
 - when moving the arrow up down the reader should inform about the item
 - when the user hits enter we should listen that the input value has set

- Not part of this story
  - API for changing default accessibility behavior like modify texts shown vs text  spoken 
  - Announce aria messages via JS  API

**Comment by manolo** [comment]
# ARIA Support Research results:

### Tools

For a full testing of ARIA implementation, we probably needed some of the popular readers like JAWS and some blind people.

But we have other developer tools that could help

1. VoiceOver in mac: it is installed by default in Mac computers and you can access with 'cmd+F5'. The main problem I found is that is is not specific of web pages and it informs about so much stuff, so to we was very noisy.
2. FireVox is a good tool, but unfortunatelly does not work in Mac.
3. ChromeVox is the best option right now since it works pretty well in Mac, and it's specific for web pages. For a good setup I'd recomend going to plugin options and:
   - Redefine ChromeVox modifier key (Cvox) to be 'Cmd+Ctrl'
   - Redefine Toggle ChromeVox key to be 'Cvox+A'

In this way is very easy to enable/disable the assistant 'Cmd+Ctrl+A', and to silence the speaker pushing 'Ctrl'

### ComboBox examples in the web to test with the assistant

Before start you should read some documentation, like , but also you can have a clear idea having a quick walk on different examples.

1. Visit the http://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box That solution is not complete since it does not announce the number of options the user have
2. A better example is http://oaa-accessibility.org/example/11/ The main problem I see is that it does not announce how to open the option box (Alt+keydown), and it does not inform whether the dropdown is opened
3. The best example I found was https://www.webkit.org/blog-files/aria1.0/combobox_with_live_region_status.html, in this example you can open the dropdown pushing space, and it informs about the status of the list, item values, etc.


### Solution adopted

Based on the 3rd example, I have added some attributes to vaadin-combo-box, but we have to consider these caveats:

- Polymer attribute binding to boolean values makes the attribute be present or not, but ARIA attributes need specific string values of 'true' 'false'
- We have to dinamically change attributes to correctly make the reader announce each selected item
- Aria does not have the 'focus' concept so we have to deal with 'select'


The final dom structure of our combo box with the significant attributes can be summarized as:

```
  <vaadin-combo-box>
    <paper-input-container>
      <label id='label></label>
      <input is="iron-input" id="input"
        role="combobox" aria-labelledby="label" aria-autocomplete="list" aria-owns="overlay"
        aria-expanded="true" aria-activedescendant="it0">
      ...
    </paper-input-container>
    <vaadin-adaptative-overlay id="overlay" role="listbox" data-selection="it0">
      <iron-drop-down>
        ...
        <iron-list>
          <div id="it0" role="option" aria-selected="true">foo</div>
          <div id="it1" role="option" aria-selected="false">bar</div>
          <div></div>
          ...
        </iron-list>
      </iron-drop-down>
      
    </vaadin-adaptative-overlay>
  </vaadin-combo-box>

```
