### ISSUE TITLE
Combo Box not working in IE 11.0.36

### ISSUE THREAD

**Issue by jay8t6** [vaadin/vaadin-combo-box#344]
The dropdown works, but none of the items are selectable on the latest version of IE. Can you guys take a look?

Browser: IE 
Version: 11.0.36

**Comment by samiheikki** [comment]
For me it is working in this example: http://plnkr.co/edit/TFtYLzNQQYvu2lQUH0PO?p=preview. Can you provide an example where the problem occurs?

**Comment by jay8t6** [comment]
We tried your demos also, its broken. The latest IE11 patch might have something to do with it. Make sure you test it out on 11.0.36

**Comment by samiheikki** [comment]
I filed a separated issue on our demos, see #345. But was the issue in the plunker example that I attached in the previous message. If yes, can you provide a screenshot?

**Comment by jay8t6** [comment]
@samiheikki I am having my team check on this. I will let you know shortly. Thanks for putting together the plunkr.

**Comment by jay8t6** [comment]
@samiheikki Sorry about the delay. but, we were able to confirm that this happens when testing on a Windows 8.1 machine running IE 11 (Version 11.0.9600.18161). Hope that helps.

**Comment by limonte** [comment]
I also can confirm the issue in Win8/IE10:

![recorded](https://cloud.githubusercontent.com/assets/6059356/21217438/e5a4df54-c2b4-11e6-9197-b7f520dd6228.gif)

BTW, it's weird that the same example works fine in Win10/IE11

**Comment by jay8t6** [comment]
@samiheikki any updates on this issue?

**Comment by m4po** [comment]
Hi guys!
we use the combo-box element in our project and we have also the problem to select the items in the overlay section in IE11 (Win8). I have fixed my problem by overwriting the __setPosition method in vaadin-combo-box-overlay-behavior (v1.3.3).
In line 136, translate3d is used, which does not work properly in IE11. 

My solution:
This.style.top = this._translateY + 'px';
This.style.left = this._translateX + 'px';

instead of
This.translate3d (this._translateX + 'px', this._translateY + 'px', '0');

Because the overlay is positioned absolute or fixed!
Works also fine in Chrome, FF and Edge. I think translate3d isn't necessary!

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
