### ISSUE TITLE
 ITEM-TEMPLATE BUG

### ISSUE THREAD

**Issue by hzmnet** [vaadin/vaadin-combo-box#439]
when  <template is="dom-if"> false the item render as blank.

https://jsbin.com/cuxebavino/edit?html,console,output

**Comment by jouni** [comment]
This is expected behavior. If you want to render a different template for other items, you should provide another dom-if template for those case. Though, I’m not sure if that works, haven’t tested.

**Comment by hzmnet** [comment]
dear, we just don't want to render other items. we just need which match true condition items. but it does not work as we expected. those not match true item also been render and insert in the menu as blank rows.

**Comment by jouni** [comment]
That’s also expected behavior. There’s no explicit design decision for this, but for now all items in the array are rendered.

If you do not want certain items to be rendered, you need to remove then from the array. I think you could also use the filteredItems property for this purpose.

If you want to be able to filter the items using the template, that would be a new enhancement, and we update the issue title to reflect that then.

**Comment by hzmnet** [comment]
sure we need to filter that. please update the title and reflect them

**Comment by Saulis** [comment]
Hi @hzmnet, this definitely sounds like you should be using the custom filtering functionality: https://cdn.vaadin.com/vaadin-combo-box/2.0.0-alpha1/demo/filtering.html#custom-filtering

Do you have an use case that cannot be achieved by using the custom filtering?

**Comment by tomivirkki** [comment]
Closing as inactive. Re-open if still relevant.
