### ISSUE TITLE
Keep Value utill new item are selecting

### ISSUE THREAD

**Issue by hzmnet** [vaadin/vaadin-combo-box#440]
how could we do if some times we want to keep value utill new item are be filter out and selecting.?

**Comment by Saulis** [comment]
Hi there!

If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then please either ask the question on our [Gitter](https://gitter.im/vaadin/vaadin-core-elements/) or submit it to [StackOverflow](http://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the `vaadin` tag to the question. 

Thanks!
