### ISSUE TITLE
Combo box dropdown items are not selectable in Windows 8  IE 11.0.43 browser

### ISSUE THREAD

**Issue by skandulapati** [vaadin/vaadin-combo-box#471]
Hi Team,

Thanks for your efforts in bringing this wonderful components to us.

I am facing one issue with combo box . Everything is working fine in chrome but whereas in IE the drop-down items are not selectable only in Windows 8 IE browser. (it works fine with windows 7 IE).

Currently we are using vaadin-combo-box 1.3.3 and we have got complete license to use officially. 

Could you please help us to resolve this issue ?

Thanks

**Comment by web-padawan** [comment]
Without a specific IE11 version and code to reproduce the issue was hard to investigate, that's why we never had enough appetite to work on it.

Also, it's worth mentioning that IE11 might contain some issues with the web components polyfills, depending on browser build version, which was most likely the case for this issue. 

We no longer support `vaadin-combo-box` version 1, and now it is very outdated. It is recommended to use the most recent version (currently 5.x) which gets all the fixes.

There hasn't been any activity in this issue for a while. Closing as stale.
