### ISSUE TITLE
List items overlap field underline

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#48]
The "GLOBAL" text can be seen partially above the blue underline.

![screen shot 2015-11-18 at 14 36 02](https://cloud.githubusercontent.com/assets/66382/11241244/c90c8fec-8e01-11e5-8665-9120f4ff561c.png)

#### Acceptance criteria

- The list items can no longer be seen outside the dropdown element in any situation

**Comment by jounik** [comment]
Tested this again, and seems like it’s only reproducible on Safari on a non-retina display.

**Comment by tehapo** [comment]
Looks like a `margin-top: 2px` on the dropdown content would fix this. But that would need to be targeted only to Safari. Maybe there would be a better alternative solution.

**Comment by jounik** [comment]
The dropdown element position calculations are somehow a little off, possibly something to do with sub-pixels.

**Comment by jounik** [comment]
Let’s continue the research for 0.5d (one person).

**Comment by platosha** [comment]
The position calculations are absolutely correct, no cross-browser differences spotted. This is Safari text rendering issue.

The issue affects both retina and non-retina displays. The text is exactly 1 device pixel off, therefore it's more noticeable on non-retina displays.

This happens only when combo box has fractional pixel offset (caused by some em-sized margins used in the page layout for ex.). Note if you check the offsets in web inspector console or somehow: `element.offsetTop` seems always rounded, but `element.getBoundingClientRect()` returns the actual fractional values.

**Comment by platosha** [comment]
### Calculations in deep

`<iron-dropdown/>` does the dropdown positioning internally. It calls `getBoundingClientRect()` method of the position target, then adds `verticalOffset` property.

`verticalOffset` is calculated by `<vaadin-adaptive-overlay/>`, this is where we can correct the dropdown position. For our case it uses `clientHeight` of the combo box. The `clientHeight` value is also rounded, and so `verticalOffset` is. With default styles it equals precisely 60px.

Even when `verticalOffset` is integer, the dropdown still could get fractional coordinates due to values returned by `getBoundingClientRect()`. This method behaviour is documented and non-specific for Safari.

Note that input underline has `position: absolute` style, its height is not included into the `clientHeight` value of the combo box (and the `verticalOffset` of the dropdown as well).

### Text rendering error proof

I've assigned the red background to `#dropdownContent`.

Safari: the dropdown background is not overlapping above the underline, but the text is
![screen shot 2015-11-30 at 11 40 02](https://cloud.githubusercontent.com/assets/247998/11468334/477e7d0a-9757-11e5-803a-5d06da9728e9.png)

Chrome: no overlapping
![screen shot 2015-11-30 at 11 44 03](https://cloud.githubusercontent.com/assets/247998/11468382/b0cbfaee-9757-11e5-8879-5d449418da61.png)

This is partly caused by `transform: translate3d()` positioning of items inside `iron-list`. Disabling the `transform` style property from inspector fixes the text overlap. However this is beyond our control, `iron-list` assigns these positions internally.

### Reproducing the rendering issue

I succeeded to reproduce this safari text rendering bug in JSFiddle: http://jsfiddle.net/fghtdh7r/6/

Safari: some text pixels are rendered outside the `overflow: hidden` container (!)
![image](https://cloud.githubusercontent.com/assets/247998/11468514/cc3bf954-9758-11e5-94dd-083b75d95e8d.png)

Safari on retina screen: the bug is less noticeable, but still there, exactly 1dpx rounding error
![image](https://cloud.githubusercontent.com/assets/247998/11468592/8057a924-9759-11e5-9a21-6c61ffc648a9.png)

Chrome: all correct
![image](https://cloud.githubusercontent.com/assets/247998/11468526/e2b18dac-9758-11e5-9027-a5a425b27aec.png)

**Comment by platosha** [comment]
### Possible solutions

I haven't discovered any fixes that could prevent the bug. Unfortunately, neither assigning `transform` on dropdown does resolve it, nor `overflow: hidden`, nor changing `-webkit-font-smoothing`. Even tried `font-family` change. Nothing.

Two possible ways of workround: we could either mask the bug or prevent the dropdown to be positioned with fractional coordinates, removing one of the bug conditions.

Way 1: mask the issue by offsetting the dropdown 1px lower. The error would still happen, but hidden with input underline. Acceptable. For that purpose I'd suggest using `scrollHeight` instead of `clientHeight` for `verticalOffset`. It would take into account the 1px underline, making the default offset 61px.

Way 2: prevent the fractional dropdown coordinates. A bit tricky, but still possible. We could calculate the rounding error for getBoundingClientRect().top and append it to `verticalOffset`. So the dropdown coordinates calculated inside `<iron-dropdown/>` would be always integer. For example:

```javascript
    _computeVerticalOffset: function(opened, positionTarget, fullScreen) {
      var top = positionTarget ? this.positionTarget.getBoundingClientRect().top : 0;
      var roundedTop = Math.round(top);
      var error = roundedTop - top;
      return error + (!fullScreen && positionTarget ? positionTarget.clientHeight : 0);
    },
```

**Comment by tehapo** [comment]
Very nice work on the investigation! :+1: 

Overall the issue sounds a bit tricky, but I would be ready to go with your suggested "Way 1" solution at this point. Any other opinions?

**Comment by jounik** [comment]
Yes, excellent research and documentation of the issue.

I’m okay with the easiest fix to this (solution 1 I presume).

**Comment by jounik** [comment]
The second solution is actually preferred as we can avoid scoping the fix to Safari only.
