### ISSUE TITLE
vaadin-combo-box with label and placeholder are not displayed correctly when the material design is applied.

### ISSUE THREAD

**Issue by caribouflex** [vaadin/vaadin-combo-box#586]
### Description

The `vaadin-combo-box`'s label and placeholder are one over the other when the material design custom style is applied.

### Expected outcome

1. The `vaadin-combo-box` label is display and when we click the `vaadin-combo-box` label go on top and the placeholder appear.
2. The `vaadin-combo-box` label is fixed on top when there is a placeholder.

### Actual outcome

The placeholder and the label are one over the other

### Steps to reproduce

1. Put a `vaadin-combo-box` element in the page.
2. Put a `vaadin-text-field` element in the page.
3. Add the vaadin-text-field material design theme.
4. Open the page in a web browser.
5. See the bug

```
<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-text-field.html">
<link rel="import" href="../bower_components/vaadin-combo-box/vaadin-combo-box.html">
<link rel="import" href="../bower_components/vaadin-text-field/vaadin-text-field.html">

<vaadin-combo-box label="City" placeholder="Enter or Choose a City" items="{{cities}}"></vaadin-combo-box>
<vaadin-text-field label="City" placeholder="Enter a City"></vaadin-text-field>
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- (Can't test) Safari 
- [x] Edge
- [x] IE 11
- (Can't test) iOS Safari
- (Can't test) Android Chrome

**Comment by jouni** [comment]
I think this relates to the fact that vaadin-text-field did not reflect `label` property as an attribute, so inside a combo box the text-field theme thought there is no label.

This has been fixed in the meantime to vaadin-text-field and it now adds a `has-label` attribute when it has a visible label.

Please reopen this issue in https://github.com/vaadin/vaadin-material-theme if you still have problems with the Material theme.
