### ISSUE TITLE
invalid property not set when the field is invalid

### ISSUE THREAD

**Issue by StarZeus** [vaadin/vaadin-combo-box#721]
### Description
Example: The `vaadin-combo-box` element does not update 'invalid' property when the internal vaadin-text-field becomes invalid

### Expected outcome
'invalid' property should be true when the internal text field is true

### Actual outcome

'invalid' property is always false

### Browsers Affected

- [ X] Chrome

**Comment by Haprog** [comment]
Sorry for a late response. Could you provide a bit of context or a use case (preferably with example code to reproduce this)? I'm a bit confused how you have configured your `vaadin-combo-box` so that the inner text field is `invalid` in some case but `vaadin-combo-box` is not.

I noticed we seem to be lacking docs for how to do validation with `vaadin-combo-box` but similar things should work as with https://cdn.vaadin.com/vaadin-text-field/2.4.3/demo/#text-field-validators-demos (using e.g. `required` or custom validators).

**Comment by web-padawan** [comment]
Closing as inactive. Let's reopen if we have a reproduction.
