### ISSUE TITLE
Combobox filtering issue - items not filter after getting focus

### ISSUE THREAD

**Issue by andreasbean** [vaadin/vaadin-combo-box#789]
Steps to reproduce:

1) create combobox and add items
2) setAllowCustomValue(true)
3) enter some text to filter items
4) click somewhere else so that the combobox loses focus
5) focus the combobox again
---> the items are not filtered although the textfield has a value

**Comment by platosha** [comment]
Hi, thanks for your issue. We have looked at it, but cannot reproduce anything wrong here.

It works as intended:

- Right after focusing, the combo-box displays all items, regardless of the current value.
- When you start typing, the items are filtered, and only the matching ones are displayed.
- When you use `setAllowCustomValue(true)`, any typed text is a allowed as a value of the combo-box, even if it does not match any of the items.
- When you type in the combo-box, and none of the items match the typed text, then no items are displayed.

Please give more information on your use case and expectations if you think that something is wrong.

**Comment by andreasbean** [comment]
Have followed the steps above? I believe its common sense that the text in the textfield (of the combobox) is a filter for the items. If you enter text, focus another element and then focus the textfield (of the combobox) again, then the items are not filtered although there is text in the textfield.
At least from my understanding this is wrong because the items are not filtered.

**Comment by andreasbean** [comment]
I'm a senior software engineer and I understand that's closing the issues is the fastest option to get rid of them. From my point of view the combobox seems to be too over engineered and buggy. Maybe it's a good idea to rewrite it from scratch?

**Comment by andreasbean** [comment]
When you say that's expected behavior does that mean that you have an internal specification for that?

**Comment by Haprog** [comment]
I find it interesting that you would want a combo box to work that way. It would be interesting to see an example if you know of any other combo box implementation which works like this. At least I don't remember seeing that kind of behaviour anywhere.

In my opinion the text field of a combo box is not really just a filter for the values. It shows the value that has currently been set (unless you've just typed it but haven't yet hit enter or unfocused the element).

I would expect that when you click (or focus) on a combo box, the intention is to change the value, and you would initially see all the predefined options. If you would only see the filtered values based on currently set value, you would need to first manually clear the text to be able to see all the available values and it wouldn't be as easy to quickly select another value anymore.

> Why is it intended that the combo-box should display all items regardless of the current value? I believe thats only the case if the value matches an item. If you allow custom values then the items should be filtered.

I also don't really understand why the opening behaviour of the dropdown should be any different when custom values are allowed.

Maybe you have a very specific use case where this behaviour would make sense. I would be interested to see a concrete example of how many and what kinds of items you have in a combo box when you expect this behaviour.

I think the current behaviour makes more sense for most common use cases, but if you can show a good use case for the behaviour you explained, it might make sense to create an issue about making this behaviour configurable.

**Comment by andreasbean** [comment]
Thank you for following up this discussion. 

> I would expect that when you click (or focus) on a combo box, the intention is to change the value, and you would initially see all the predefined options. If you would only see the filtered values based on currently set value, you would need to first manually clear the text to be able to see all the available values and it wouldn't be as easy to quickly select another value anymore.

I agree and for a classic combobox this was never an issue. In the simple most case the value is not editable at all. There was this small triangle to open the drown down and select another value.

Your implementation differs first of all, the box is opened automatically and there is no triangle to open it. Next, the value is editable. And finally, if you setAllowCustomValues to true, a custom value is accepted.

That said, it's clear that your combobox has more usecases than the original one. I'm only interested in the one where custom values are allowed. In my case I want to enter a value into the textfield and see existing items. I may choose one or not. If the items looses focus and I get back to the textfield again, I just want continue where I was. I don't see the point why I would need all items in the box when there is still text in textfield. I may erase or clear the text to get all items again.

Can you point out why it should make sense to show all items when there is still text in the textfield? For me this is just inconsistent. I custom values are not allowed than the text field is cleared on lost focus. This makes sense to me and also that in this case all items are shown. But concerning custom values it makes no sense to me.

**Comment by andreasbean** [comment]
Have a look at the attached images, before and after loosing and getting focus.
![before](https://user-images.githubusercontent.com/40847723/54612805-e7063800-4a59-11e9-906b-4f97fecd50bc.png)
![after](https://user-images.githubusercontent.com/40847723/54612807-e7063800-4a59-11e9-928e-b7748b1e8913.png)

**Comment by Haprog** [comment]
> I agree and for a classic combobox this was never an issue. In the simple most case the value is not editable at all. There is this small triangle to open the drown down and select another value.

I think here you're describing what is usually called a "select" or "drop down list" component (when the value is not editable, see e.g. [vaadin-select](https://github.com/vaadin/vaadin-select)). "combo box" commonly means a component which also has an editable text field (https://en.wikipedia.org/wiki/Combo_box).

> First of all, the box is opened automatically and there is no triangle to open it.

You're right that it's opened automatically (e.g. on click or focus) for enhanced UX, but there is still the visible "triangle" icon too (which you can also click) but in this case the main purpose of the icon is just to indicate that there is a dropdown available and to distinguish the component from a regular text field visually.

> If the textfield looses focus and I get back to the textfield again, I just want continue where I was. I don't see the point why I would need all items in the box when there is still text in textfield.

Are you saying you would want to be able to type something into the field and to be able to unfocus the field leaving the combo box text field in a state where it would still show the text you typed but would not set it as the current value (still keeping the possible old value as the currently set/selected value even though you have typed something in it and left the field)?

Currently it works so that whenever you leave the field (e.g. by clicking elsewhere or focusing some other element) it is the same as confirming the written value by pressing Enter so the written value will be set as the current value (and filtering is cleared)

> when there is still text in textfield

This is a bit weird for me since there is always text in the field when there is a value selected (other than empty string) because the purpose of the text field is to show the current value (when you aren't editing it or after you have selected any value/item).

> If custom values are not allowed than the text field is cleared on lost focus. This makes sense to me and also that in this case all items are shown.

This isn't true (except in the specific case when the currently set value is an empty string).

When the text field loses focus it will attempt to set the combobox value to the value that was written in the text field, but if the value is invalid (when custom value is not allowed), then the value of the text field will be reset to the current value of the combo box (which might be the text of any item which was selected before you started typing in the field, or it could be empty string if nothing was selected).

**Comment by tomivirkki** [comment]
*Image 1:*
You're filtering the pre-existing value options of the field, only the options with "pan" are listed. "pan" is the filter in this case.

Then you blur the field -> since, you've enabled `allowCustomValue`, "pan" actually becomes the _value_ for the field.

*Image 2:*
You re-open the dropdown, "pan" is no longer a _filter_ but a _value_ so all the other options are listed there also.

If you had typed "Panik" (one of the existing options) into the field in step 1. you'd only see that option before closing the field as "Panik" would be the filter. After blurring it, "Panik" would've become the value. Once re-opening the field, you'd see all the available options and "Panik" marked as selected = _not only having "Panik" listed_, right?

The two cases are exactly the same with the difference that "pan" isn't one of the pre-listed values but a _custom_ one.

**Comment by Haprog** [comment]
After looking at your screenshots I'm still not convinced that it would be any better (at least as a default behaviour) if it would filter the values when you focus the element again in case there is a custom value set. That would also make the behaviour inconsistent if you would still want it not to filter the values when the set value is one from the list and not a custom value.

If you want you can open a new issue (a feature request) about providing some configuration option to make it behave like this, but I can't tell now if that would be something we would like to implement (maybe if it looks like it would be useful to more people).

But right now you could get the behaviour you described with `vaadin-combo-box` with a bit of custom code like:  
```js
myComboBox.addEventListener('opened-changed', e => {
  if (e.target.opened) e.target._filterFromInput();
})
```

(Needs a bit more code if you don't want to apply the filter when one of the predefined items is selected instead of a custom value.)

Or if you want to reuse this in many places, you could create your own combo box component which extends `<vaadin-combo-box>` (`Vaadin.ComboBoxElement`) and do this in your component, so you wouldn't need to set this event listener separately for all instances where you use `<vaadin-combo-box>`.

**Comment by andreasbean** [comment]
I'm almost giving up, on the other hand the combobox is not usable for me. At the moment I have a forked version due to other bugs. I could change the behaviour to fit my needs on my branch but keeping the forked version forever is not very satisfying.

Do you have an example of how to extend a vaadin component on the client and server side? I just know how to extend classes on the server but it's unclear to me how to extend it on the client side so that the server side components still connects to the descendant client side class.

**Comment by andreasbean** [comment]
There is one more point to mention: 
**The argument that the whole list should be presented to the user is based on the assumption that there are only a few elements in the list where the user can choose from. If there are hundreds of items in the list the unfiltered content is never useful. In that case it is preferable to filter the items with the existing value when the drop down is opened.**

**Comment by tomivirkki** [comment]
This is just the default behaviour of `items` API. If you prefer custom behaviour, you can skip `items` and create a [`dataProvider`](https://cdn.vaadin.com/vaadin-combo-box/4.2.6/#/elements/vaadin-combo-box#property-dataProvider) for the purpose instead. One of the arguments for it is the current filter. Obviously, you can also use the current `comboBox.value` in the `dataProvider` to exclude all the other values from the result set if that's what you want to do.

**Comment by andreasbean** [comment]
I want to follow up the idea of extending the ComboBox on both the server and client side. I couldn't find an example in the documentation how to do that. Can you please point out how to extend a component on the client side and point out how to extend the server side part so that the component is still working.

**Comment by Haprog** [comment]
@andreasbean I understand that it shouldn't be hard to do, but I'm not aware of any actual example extending both client side and server side together. I posted this as a topic idea for a tutorial (to https://vaadin.com/tutorials) in our internal Slack. Hopefully we will make a tutorial about this. I think it would be very useful to many. It's also possible for an external to contribute a tutorial by submitting a PR here https://github.com/vaadin-learning-center/learning-content

Here's a summary of how the extending should be possible to do (from what I heard):
1. Extend the client-side class
2. Register it as a new custom element with your own tag name
3. Extend the server-side class and add a `@Tag` annotation with the tag name of your extended custom element.

And probably you also need to add `@HtmlImport` annotation in the Java class to import your client-side component.

**Comment by andreasbean** [comment]
Unfortunately we had to remove the ComboBox from our application due to the many bugs it has. I will communicate that situation to your sales office since this is not acceptable for us.

**Comment by pekam** [comment]
Hi, @andreasbean! Could you clarify what are these _many bugs_ that are blockers for you? As described above, this particular issue is considered to work as expected.

We made a new maintenance release of the Flow component today with some fixes: https://github.com/vaadin/vaadin-combo-box-flow/releases/tag/2.1.3

We are aware that at least the custom value feature has issues when used with the Java API, but fixing these has not had a high priority so far.

It would be useful to know which issues are blocking your application development (besides this one).
