### ISSUE TITLE
When you say that's expected behavior does that mean that you have an internal specification for that?

### ISSUE THREAD

**Issue by andreasbean** [vaadin/vaadin-combo-box#793]
When you say that's expected behavior does that mean that you have an internal specification for that?

_Originally posted by @andreasbean in https://github.com/vaadin/vaadin-combo-box/issues/789#issuecomment-474341311_

**Comment by web-padawan** [comment]
Here is the spec that we component should be following now:

![combo box state transitions](https://user-images.githubusercontent.com/66382/46010604-fbc9ca80-c0cb-11e8-94ca-5e4a70324f45.png)

Extracted from https://github.com/vaadin/vaadin-combo-box/issues/622#issuecomment-424300282

It can be a bit outdated, but overall there hasn't been any breaking changed in terms of the combo-box behaviour since the version 4.0.0

There is no need for separate issue. We are following the discussion in #789 even though it has been marked as "won't fix" so I would prefer to continue there.

**Comment by web-padawan** [comment]
Closing per above comment.
