### ISSUE TITLE
[Question] Is cancel() designed to be used externally, is is that an internal-only method?

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-combo-box#833]
I can't find a point in the lifecycle of the component where I can call cancel() that will return the combo box to the previous setting. In my use case, I need to verify with the user before they change the value. I've tried to listen to `value-changed`, `selected-item-changed` and just plain old `changed`, but everything seems fire after `value` is set, so the `cancel()` logic just reverts it back to itself.

From what I can see, `cancel()` looks to be more of a reset if anything goes wrong in the lifecycle of the component, not something designed to do what I was looking for. There are workarounds (saving value in external variable, etc), but I was hoping that this was a feature of the component.

**Comment by Haprog** [comment]
The documentation for `cancel()` could be improved to be more clear on what it exactly does or when can you use it.

It is a public method (as you can also see it documented in the API docs). What it does is set the visible input value to match the current `comboBox.value` property (if they aren't the same). Basically `cancel()` is internally used only in the `_onEscape` handler atm. I think it's only useful when the user has written something in the combo box but hasn't yet "committed the value" by unfocusing the field or hitting enter. Or if you have programmatically set the `comboBox.filter` property and then calling `cancel()` will change it back to the same as `value`.

As you mention, it's too late to try and call `cancel()` in `value-changed` or `selected-item-changed` events because then the `value` property has already been updated to the new value.

For your use case of confirming the selected value, we would need to implement some new feature (maybe a new event) to make it easy. Feel free to open a new feature request issue about this.

Atm. to make it work in your use case you would probably need to cache the selected value yourself (in your own app logic) and then revert it in some code triggered by e.g. `value-changed` (but changing/reverting it in this case will trigger another `value-changed` event so make sure you handle it in a way that doesn't result in an endless loop).

Closing this as a question.
