### ISSUE TITLE
The latest version reported on npm-js is 2.3.10, but the real latest version is 2.4.3.

### ISSUE THREAD

**Issue by marcovanetti** [vaadin/vaadin-combo-box#835]
### Problem
The latest version reported on npm-js is 2.3.10, but the real latest version is 2.4.3.
Please fix it.
Source: https://www.npmjs.com/package/@vaadin/vaadin-text-field

### Description
Requiring a "vaadin-combo-box" component (e.g. executing a WebPack package) generates an exception because a dependent control, "vaadin-text-field", was already declared before but with a different version. 

### To reproduce
Create a project including as dependencies the latest versions of "vaadin-combo-box" (use * as version in package.json) and "vaadin-text-field" (use * as version in package.json). Since "vaadin-combo-box" has a dependency on "vaadin-text-field" version "^2.4.3" but the official latest version of "vaadin-text-field" is "2.3.10", the problem appears.

### Expected outcome
"vaadin-combo-box" should be required without exceptions

### Actual outcome
Exception thrown:
"Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry"

Stack trace:
./node_modules/@vaadin/vaadin-combo-box/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js
./node_modules/@vaadin/vaadin-combo-box/node_modules/@vaadin/vaadin-text-field/theme/lumo/vaadin-text-field.js
./node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box-styles.js
./node_modules/@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js
./node_modules/@vaadin/vaadin-combo-box/vaadin-combo-box.js

### Browsers Affected
Tested on Safari 12.1 and Chrome 76 on MacOS.

**Comment by Haprog** [comment]
This has been fixed now (for this component). Thanks for the report!

We have currently slightly flawed logic in component release tooling which we know about and need to fix so that this problem doesn't reoccur. Currently this happens if we release a maintenance release for an older minor version of the repository and it updates `latest` which now needs to be manually corrected or it will correct itself when releasing a new version from the latest stable branch.
