### ISSUE TITLE
Spaces are removed from dropdown list

### ISSUE THREAD

**Issue by Imallek** [vaadin/vaadin-combo-box#837]
### Description
Spaces are removed from selections list

### Expected outcome
Space must not get removed automatically.

### Actual outcome
Spaces get removed.

### Live Demo
In combo-box label, I can set String with all space in the object
 obj.label = `   (space)(space)(space)(space)   1- OBJECT1   (space)(space)(space)(space)              `;
and it is displayed that way WITH spaces.
But all spaces are removed in the dropdown and they are displayed in dropdown as
 "1-OBJECT1"

### Steps to reproduce
When data is populated, spaces dont get removed from label, but all spaces get removed from the selections list.

### Browsers Affected

- [ ] Chrome

**Comment by Haprog** [comment]
Spaces are not removed by combo box. The issue here is how HTML works, when it normally collapses consecutive spaces unless you use non-breaking spaces or a style like `white-space: pre-wrap;`.

Your options are to either add the above style to the items in the combo-box overlay (using a theme module) or to convert the spaces in your value strings to non-breaking spaces.

You can set a non-breaking space in a JS string as `'\u00a0'`.

E.g.
```js
comboBox.items = ['\u00a0\u00a0\u00a0\u00a0\u00a01- OBJECT1\u00a0\u00a0\u00a0\u00a0\u00a0'];
```

Or you could do a string replace operation to just convert all regular spaces to non-breaking spaces like:
```js
comboBox.items = ['     1- OBJECT1     '].map(v => v.replace(/ /g, '\u00a0'));
```

But note that when reading the selected value it would then also contain the non-breaking spaces instead of regular spaces so you might need to reverse the conversion then using the selected value depending on what you do with it.

**Comment by Imallek** [comment]
Thanks @Haprog
