### ISSUE TITLE
Closing fullscreen mode causes zoom level issues on iOS

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-combo-box#86]
After closing the fullscreen mode, iOS sometimes zooms in the page instead of returning to the original view. In some tests it was even more frequently reproduced if the HTML document already has a viewport meta tag.

`<meta name="viewport" content="width=device-width">`

From http://wc.demo.vaadin.com/combo-box-usertest/index.html:
![screen shot 2015-12-11 at 10 36 33](https://cloud.githubusercontent.com/assets/368220/11739764/7a2be768-9ff6-11e5-9515-4309f7d83c92.png)

**Comment by jounik** [comment]
1d timebox for researching a fix or an alternative solution to the current.

**Comment by tomivirkki** [comment]
Tried this with a couple of different approaches. Basic idea was instead of manipulating the viewport meta tag to scale the dropdown itself to fit the screen.

Issues related with zooming: On IOS, when the input field gets focused, browser zooms in towards the input (on combo box open or input re-focus after scrolling the items). So to avoid the original issue (zoom level altered after closing the dropdown), we'll need to disable zooming on IOS while the dropdown is open = viewport meta tag manipulation. Can't avoid that apparently.
Altering the viewport tag would reset the zoom level on Android devices, so zooming must be enabled at all times (even with the dropdown open).

Issues related with scaling: First I tried scaling the dropdown content with transform: scale. The scaled content is blurry (especially on IOS) if it needs to be scaled up. The amount of blur depends on the zoom level on dropdown open.
Also tried scaling with css 'zoom'. With that approach upscaled content isn't blurry but font scaling has issues (especially on IOS): some items might have scaled font, some might not.
