### ISSUE TITLE
combo-box incompatible with paper-header-panel?

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-combo-box#92]
Opening a combo-box on a page with a `paper-header-panel`, shows it incorrectly grayed out and under the header on iPhone. 

![screenshot_20151214-090812](https://cloud.githubusercontent.com/assets/883698/11788055/d6d2fc96-a243-11e5-9c40-cbbd2d4de2cc.png)

![img_0347](https://cloud.githubusercontent.com/assets/883698/11788139/5a062cf0-a244-11e5-8574-94f8690f4caa.PNG)

**Comment by jounik** [comment]
1d timebox for the research

**Comment by platosha** [comment]
### The cause

In fullscreen mode on iOS, the dropdown node is still placed inside `vaadin-combo-box` and uses `absolute` position with some high `z-index` value to place it in front of the page and the semi-transparent black backdrop. The backdrop is also `absolute` and appended to `document.body`.

Inside `paper-header-panel` there's an `overflow: auto` container for the main page content with scrolling, `#mainContainer`. One of its styles, namely `-webkit-overflow-scrolling: touch`, introduces a new stacking context, which affects all its child z-indexes. That’s why the dropdown’s `z-index` no longer surpasses the backdrop.

### Not a single cause, but a group

One could suggest as a workaround: when opening fullscreen dropdown on iOS, just check the containers and temporarily reset the `-webkit-overflow-scrolling` to the default `auto` value. This would mostly fix the usage inside `paper-header-panel`.

But unfortunately, it’s not a single property that could cause this kind of an issue. There’s a bunch of other css properties that also [introduce a stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) (opacity, z-index, transform, will-change, etc...). Setting any of them to something non-default on any of the `vaadin-combo-box` containers would case the similar issue.

There’s also another issue discovered when combo-box on iOS inside a `paper-header-panel`. It’s `#mainContainer` uses `overflow: auto`, and this also affects the fullscreen dropdown, possibly cuts the dropdown edges in case if `#mainContainer`’s width is not stretched to fill the viewport.

### Solution idea

In order to fix all the issues with parent stacking contexts and hidden overflows, we should at least move the fullscreen dropdown node out of the combo box and attach it to the body. Possibly giving another try on making it `fixed` instead of `absolute`.

I haven't prototyped the solution yet, this would my next step for this research. To be continued...
