### ISSUE TITLE
Loading is not removed on data provider return 

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-combo-box#963]
### Description

Loading persists after blurring  a `vaadin-combo-box`  with pending requests and is not removed afterwards.

### Expected outcome
Loading should be removed when the data provider returns

### Actual outcome
Loading persists
![combo-box-loading-issue](https://user-images.githubusercontent.com/28783969/97414088-3c7c1980-190c-11eb-8a30-cb2a4e05ae39.gif)

### Live Demo

Can be reproduced in the `Lazy Loading` example: https://vaadin.com/components/vaadin-combo-box/html-examples/combo-box-basic-demos#lazy-loading

### Steps to reproduce
1. Inspect the `vaadin-combo-box` in the 
2. Verify that `$0.loading` is `false`
3. Type something in the combo-box filter and immediately press `tab` to blur the field.
4. Verify that `$0.loading` is `true` and never changes back to `false`

### Browsers Affected
Tested on the following
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by sosa-vaadin** [comment]
I was unable to reproduce this bug in v6.0.0.
I tried on Chrome, Firefox, Safari and Opera.

https://user-images.githubusercontent.com/76832183/108627876-6085dc80-7460-11eb-857e-849aebfb3e4a.mov

The `loading` attribute gets removed after the fetch callback returns. In the above example, it takes 2 seconds since there is a 2-second timeout to make the callback last a significant amount of time (as is the demo example).
