### ISSUE TITLE
Keyboard selection should accept space

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-combo-box#97]
When browsing items with my keyboard, I expect to be able to select an item with space the same way as in a native select or paper-dropdown. Currently hitting space only types into the field.

**Comment by Saulis** [comment]
They are different kind of components, combo-box has an input field which has the focus by default for quick and easy filtering. In order to make space selection work we would need to remove focus from the input field when keyboard navigating - which in turn forces the user to refocus the input field when he/she wants to change the filter.

Are you sure about the native select? Tried http://nativeformelements.com/ with Windows Chrome + FF and the `<select>` only selected with enter. Anyways, I _personally_ don't see users actually expecting to be able to use space selection with a combo-box and implementing it (with the focus shifting described) would be a poor tradeoff UX-wise in my view.

**Comment by vaadin-marcus** [comment]
On Mac, native select options can be selected with space.

**Comment by platosha** [comment]
Won’t fix. As mentioned, this conflicts with typing in the input field.
